server:
  port: 11005
spring:
  application:
    name: jcallpy
  datasource:
    url: jdbc:mariadb://10.104.1.206:3306/jcallpy?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: zc1021
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
    
jcp:
  file:
    path: /Users/cong/Downloads/jcallpy/

logging:
  level:
    com.congcong.jcallpy: debug
